"""Constantes visuais compartilhadas pela identidade DMS."""

MONOGRAM_BACKGROUND = "#1D3043"
MONOGRAM_BORDER = "#3F78AA"
MONOGRAM_FOREGROUND = "#D9EBFB"
MONOGRAM_BADGE_WIDTH = 38
MONOGRAM_BADGE_HEIGHT = 34
MONOGRAM_BADGE_BORDER = 1
MONOGRAM_BADGE_RADIUS = 5
